FROM gcr.io/distroless/static-debian13@sha256:eca24e67792afe660769e84c85332d9939772e7f76071597d179af96ac4e9e4f
WORKDIR /app

ARG TARGETARCH

COPY backend-bin/linux_${TARGETARCH}/app /app/app
COPY ui-build/build /app/internal/ui/build

VOLUME ["/data"]
EXPOSE 8080
USER 1000:1000
ENTRYPOINT ["/app/app"]