FROM gcr.io/distroless/static-debian13@sha256:28efbe90d0b2f2a3ee465cc5b44f3f2cf5533514cf4d51447a977a5dc8e526d0
WORKDIR /app

ARG TARGETARCH

COPY backend-bin/linux_${TARGETARCH}/app /app/app
COPY ui-build/build /app/internal/ui/build

VOLUME ["/data"]
EXPOSE 8080
USER 1000:1000
ENTRYPOINT ["/app/app"]