FROM gcr.io/distroless/static-debian13@sha256:f2ea2709ac8db56323cbd7d014277f32cb572d9ea124b0076f7aafe5980678fe
WORKDIR /app

ARG TARGETARCH

COPY backend-bin/linux_${TARGETARCH}/app /app/app
COPY ui-build/build /app/internal/ui/build

VOLUME ["/data"]
EXPOSE 8080
USER 1000:1000
ENTRYPOINT ["/app/app"]